# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = migrations

# template used to generate new migration files
# file_template = %%(year)d_%%(month).2d_%%(day).2d_%%(hour).2d%%(minute).2d-%%(rev)s_%%(slug)s

# sys.path pathpower to search for modules.
# prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# timezone = UTC

# max length of characters to clone to slug
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow curly braces in the version_locations variable
# version_locations_key_style = standard

# logging configuration is defined at the bottom.

[post_write_hooks]
# post_write_hooks defines scripts that are run after a new migration file is generated.
# hooks are defined as hook_name.type, hook_name.options, etc.

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARNING
handlers = console
qualname =

[logger_sqlalchemy]
level = WARNING
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
